server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms?useSSL=true
    username: root
    password: shinian
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:

      ddl-auto : update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect